puts "The student of Villains Academy"
puts "------------"
puts "Dr. Hannibal Lecter"
puts "Darth Varder"
puts "Nurse Ratched"
puts "Micheal Corleone"
puts "Alex DeLarge"
puts "The Wiched Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
